# docker-compose.yml
services:
  socket_client_arm64v8-debian-python3-qt-vivante_bullseye_release_69b0ba86-a0f3-4b98-82c1-753cfc4e1831:
    depends_on:
    - weston
    device_cgroup_rules:
    - c 199:* rmw
    - c 226:* rmw
    devices: []
    image: gcldndocker/test_client:v0
    ports: []
    volumes:
    - /tmp:/tmp:rw
    - /dev/dri:/dev/dri:rw
    - /dev/galcore:/dev/galcore:rw
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    environment:
    - ACCEPT_FSL_EULA=1
    image: torizon/weston-vivante:2
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '2.4'
